### ISSUE TITLE
Input alignment preparation

### ISSUE THREAD

**Issue by apredeus** [santeripuranen/SuperDCA#4]
Hello Santeri, 

I was interested in using your tool on my dataset. However, I can't seem to find how was the input alignment generated. MGen paper doesn't mention it at all, and Plos Genetics paper describes alignment to a reference genome - albeit the text later refers to it as "whole genome alignment". 

Would you please clarify? Thank you in advance!

**Comment by santeripuranen** [comment]
I'm closing this issue, as it's related to the problem of genome alignment generation more generally, and not to the SuperDCA project per se.
